FROM node:24.15.0-slim
RUN apt-get update && apt-get install -y --no-install-recommends python3 g++ clang default-jdk-headless procps && rm -rf /var/lib/apt/lists/*
RUN npm install -g pnpm@10.32.1
WORKDIR /usr/src/app
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile
COPY . .
RUN chown -R node:node /usr/src/app
USER node
CMD ["pnpm", "test:all"]
